env: "docker"

db_url: "postgres://user:password@postgres:5432/myDb?sslmode=disable"
admin_token: "admin_token"

http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s

redis:
  addr: "redis:6379"
  password: ""
  db: 0
